/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function formatFlag(step: string, salt?: string | undefined | null): string
export declare function formatFlagFromContext(context: string, step: string, salt?: string | undefined | null): string
export declare function getSeedOrNull(): string
