/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function formatFlag(step: string, salt?: string | undefined | null): string

export declare function formatFlagFromContext(context: string, step: string, salt?: string | undefined | null): string

export declare function getSeedOrNull(): string
